FA.JustBlog/FA.JustBlog.MVC/Areas/Admin/Controllers/UserAdminController.cs
using FA.JustBlog.Entity.Entity;
using FA.JustBlog.Models.AppUser;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Net;

namespace FA.JustBlog.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin")]
    public class UserAdminController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly RoleManager<AppRole> roleManager;


        public UserAdminController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }
        [Route("IndexUser")]
        [Authorize(Roles = "Contributor, Blog Owner")]
        public async Task<IActionResult> Index()
        {
            var y = await userManager.Users.ToListAsync();
            return View(y);
        }
        [Route("DetailUser")]
        [HttpGet]
        [Authorize(Roles = "Contributor, Blog Owner")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var user = await userManager.FindByIdAsync(id);

            ViewBag.RoleNames = await userManager.GetRolesAsync(user);

            return View(user);
        }
        [Route("CreateUser")]
        [HttpGet]
        [Authorize(Roles = "Blog Owner")]
        public async Task<IActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await roleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }
        [Route("CreateUser")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Blog Owner")]
        public async Task<IActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser()
                {
                    UserName = userViewModel.Email,
                    Email = userViewModel.Email,
                    Name = userViewModel.Email
                };
                var result = await userManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (result.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var results = await userManager.AddToRolesAsync(user, selectedRoles);
                        if (!results.Succeeded)
                        {
                            ModelState.AddModelError("", "Failed");
                            ViewBag.RoleId = new SelectList(await roleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Error");
                    ViewBag.RoleId = new SelectList(roleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(roleManager.Roles, "Name", "Name");
            return View();
        }

        [Route("EditUser")]
        [HttpGet]
        [Authorize(Roles = "Blog Owner")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var userRoles = await userManager.GetRolesAsync(user);
            var roles = await roleManager.Roles.ToListAsync();
            var roleItems = roles.Select(role =>
                 new SelectListItem(
                     role.Name,
                     role.Id.ToString(),
                     userRoles.Any(ur => ur.Contains(role.Name)))).ToList();
            var result = new UserViewModel()
            {
                Email = user.Email,
                Id = user.Id.ToString(),
                RolesList = roleItems
            };

            return View(result);
        }
        [Route("EditUser")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Blog Owner")]
        public async Task<IActionResult> Edit(UserViewModel editUser)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return NotFound();
                }
                var userRoles = await userManager.GetRolesAsync(user);

                var rolesToAdd = new List<string>();
                var rolesToDelete = new List<string>();
                foreach (var role in editUser.RolesList)
                {
                    var assignedInDb = userRoles.FirstOrDefault(ur => ur == role.Text);
                    if (role.Selected)
                    {
                        if (assignedInDb == null)
                        {
                            rolesToAdd.Add(role.Text);
                        }
                    }
                    else
                    {
                        if (assignedInDb != null)
                        {
                            rolesToDelete.Add(role.Text);
                        }
                    }
                }
                if (rolesToAdd.Any())
                {
                    await userManager.AddToRolesAsync(user, rolesToAdd);
                }
                if (rolesToDelete.Any())
                {
                    await userManager.RemoveFromRolesAsync(user, rolesToDelete);
                }

                user.Name = editUser.Email;
                user.Email = editUser.Email;
                userManager.UpdateAsync(user);

                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View(editUser);
        }
        [Route("DeleteUser")]
        [Authorize(Roles = "Blog Owner")]

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var result = await userManager.DeleteAsync(user);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Delete Failed");
                return View();
            }
            return RedirectToAction("Index");
            return View();
        }

       
    }
}

FA.JustBlog/FA.JustBlog.MVC/Areas/Admin/Views/UserAdmin/Create.cshtml
@using FA.JustBlog.Models.AppUser
@model RegisterViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Share/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title.</h2>


<div class="card-block">
    <form asp-controller="UserAdmin" asp-action="Create" asp-area="Admin" method="post" class="md-float-material">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input asp-for="Email" type="email" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Password" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input asp-for="Password" type="password" class="form-control">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="RePassword" class="col-sm-2 col-form-label">RePassword</label>
            <div class="col-sm-10">
                <input asp-for="RePassword" type="password" class="form-control">
                <span asp-validation-for="RePassword" class="text-danger"></span>
            </div>
        </div>

    <!-- end of form -->
    <div class="form-group">
        <label class="col-md-2 control-label">
            Select User Role
        </label>
        <div class="col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, item.Text, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Create" />
        </div>
    </div>
    </form>
    </div>

FA.JustBlog/FA.JustBlog.MVC/Areas/Admin/Views/UserAdmin/Details.cshtml
@using FA.JustBlog.Entity.Entity
@model AppUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Share/_LayoutAdmin.cshtml";
}

<h2>Details.</h2>

<div class="card">
<div class="card-block table-border-style">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                   <th>Roles</th>
                </tr>
            </thead>
            <tbody>
                    <tr>
                        <td>@Model.Name</td>
                        @if (ViewBag.RoleNames.Count == 0)
                        {
                                <td>No roles found for this user.</td>
                        }else {
                      <td>
                                @foreach (var item in ViewBag.RoleNames)
                                {
                                    <span>@item , </span>
                                }
                      </td>  
                        }
                    
                    </tr>
            </tbody>
        </table>
    </div>
</div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FA.JustBlog/FA.JustBlog.MVC/Areas/Admin/Views/UserAdmin/Edit.cshtml
@using FA.JustBlog.Models.AppUser
@model UserViewModel

@{
    Layout = "~/Areas/Admin/Views/Share/_LayoutAdmin.cshtml";

}

<h2>Edit.</h2>


<div class="card-block">

    <form asp-controller="UserAdmin" asp-action="Edit" asp-area="Admin" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label" hidden>Id</label>
            <div class="col-sm-10">
                <input asp-for="Id" type="text" hidden class="form-control">
               
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <h4 class="mb-3">Roles</h4>

        <div class="my-3">

            @for (int i = 0; i < @Model.RolesList.Count(); i++)
            {
                <div class="form-check">
                    @Html.CheckBoxFor(c => @Model.RolesList[i].Selected)
                    @Html.HiddenFor(h => @Model.RolesList[i].Value)

                    @Html.LabelFor(l => @Model.RolesList[i].Selected, @Model.RolesList[i].Text, new {@class="form-check-label"})
                    @Html.HiddenFor(h => @Model.RolesList[i].Text)
                </div>
            }
        </div>

        <hr class="my-4">

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </form>
    </div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FA.JustBlog/FA.JustBlog.MVC/Areas/Admin/Views/UserAdmin/Index.cshtml
@using FA.JustBlog.Entity.Entity
@model IEnumerable<AppUser>
@{
    ViewBag.Title = "Roles Management";
    Layout = "~/Areas/Admin/Views/Share/_LayoutAdmin.cshtml";

}




<h2 class="text-center">User Management</h2>
<h4 class="text-success time-hide">@TempData["Message"]</h4>
<div class="btn btn-primary mb-3">
    <a href="@Url.Action("Create", "UserAdmin")" class="text-white text-decoration-none"><span class="fas fa-plus"></span></a>
</div>

<div class="card">
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td class="d-flex">
                                <a href="@Url.Action("Edit", "UserAdmin", new { id = item.Id})" class="mr-3"><i class="far fa-edit"></i></a>
                                <a href="@Url.Action("Details", "UserAdmin", new { id = item.Id})" class="mr-3"><i class="fas fa-info-circle"></i></a>
                                <form asp-action="Delete" asp-controller="UserAdmin" asp-area="Admin" asp-route-id="@item.Id" method="post">
                                    <button type="submit" onclick="return confirm('Are you sure to delete this post?');" class="bg-transparent border-0 text-danger"><i class="far fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>