FA.JustBlog/FA.JustBlog.MVC/Controllers/PostController.cs
using FA.JustBlog.Models.Models.Post;
using FA.JustBlog.Service.PostService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using X.PagedList;

namespace FA.JustBlog.MVC.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly ILogger<PostController> _logger;
        public PostController(IPostService postService, ILogger<PostController> logger)
        {
            _postService = postService;
            _logger = logger;
        }

        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            try
            {
                var post = _postService.GetAll();
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                if (!String.IsNullOrEmpty(searchString))
                {
                    post = post.Where(x => x.Title.Contains(searchString.Trim()));
                }
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                return View(post.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "");

            }
            return View();
        }




        public IActionResult GetPostByCategory(string category)
        {
            try
            {
                var post = _postService.GetPostByCategory(category);
                if (post == null)
                {
                    return BadRequest();
                }
                return View(post);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "");
            }
            return View();
        }

        public IActionResult GetPostByTag(string tag)
        {
            try
            {
                var post = _postService.GetPostByTag(tag);
                if (post == null)
                {
                    return BadRequest();
                }
                return View(post);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "");
            }
            return View();


        }
        public IActionResult Detail(Guid id)
        {
            try
            {
                var post = _postService.GetByPostId(id);
                if (post == null)
                {
                    return BadRequest();
                }
                return View(post);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "");
            }
            return View();

        }

        public IActionResult Details(int year, int month, string title)
        {
            try
            {
                var posts = _postService.GetPostByMonthYear(year, month, title);
                if (posts == null)
                {
                    return BadRequest();
                }
                return View("Detail", posts);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "");
            }
            return View();
        }



    }
}

FA.JustBlog/FA.JustBlog.MVC/Views/Post/Detail.cshtml
@using FA.Common
@using FA.JustBlog.Models.Models.Post
@using FA.JustBlog.Entity.Entity
@model PostModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/admin/js/jquery/jquery.min.js"></script>
<div class="item">
    <div class="post_s_item">
        <div class="post_text">
            <a class="cat" href="@Url.Action("GetPostByCategory", "Post", new { category = Model.CategoryName})">@Model.CategoryName</a>
            <h2 class="text-primary">@Model.Title</h2>
            <p>
                @Html.Raw(@Model.PostContent)
            </p>
            <div class="date text-secondary">
                <i class="fa fa-calendar" aria-hidden="true"></i>  Posted
                @TimeOn.Time(Model.PostedOn)
                with rate @Model.Rate by @Model.ViewCount @(Model.ViewCount <= 1 ? "view" : "views")
            </div>

        </div>
    </div>

</div>
<div class="comment-form mb-5">
    <h4>Enter a comment</h4>
    <form>
        @Html.HiddenFor(x => x.Id, new { id = "post-id" })
        <div class="form-group form-inline">
            <div class="form-group col-4">
                <input type="text" class="form-control border border-primary" id="name" name="name" placeholder="Enter name" onfocus="this.placeholder = ''">
            </div>
            <div class="form-group col-7">
                <input type="email" class="form-control border border-primary" id="email" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''">
            </div>
        </div>
        <div class="form-group col-12">
            <input type="text" class="form-control border border-primary" id="commentHeader" name="commentHeader" placeholder="Enter comment header" onfocus="this.placeholder = ''">
        </div>
        <div class="form-group col-12">
            <input class="form-control mb-10 border border-primary" rows="3" id="commentText" name="commentText" placeholder="Enter comment" onfocus="this.placeholder = ''">
        </div>
        <div class="col-12">
            <button type="button" id="submit-comment" class="btn btn-success">Comment</button>
        </div>
    </form>
</div>

<div id="myComment" class="comments-area">
    <h4 id="count-comment">@Model.CommentList.Count@(Model.CommentList.Count <= 1 ? "Comment" : "Comments") </h4>
    <div class="comment-list">
        @foreach (var item in Model.CommentList.OrderByDescending(c => c.CommentTime).ToList())
        {
            <div class="single-comment justify-content-between d-flex mb-2">
                <div class="user justify-content-between">
                    <div class="thumb d-flex">
                        <div><a class="h4" href="#">@item.Name</a><i> - @item.CommentTime.ToString("dddd, dd MMMM yyyy")</i></div>
                    </div>
                    <div>
                        <p class="date h6">@item.CommentHeader</p>
                        <p class="comment">@item.CommentText</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>





<script>
    $("#submit-comment").click(function () {
        let postId = $("#post-id").val();
        let name = $('#name').val().trim();
        let email = $('#email').val().trim();
        let commentHeader = $('#commentHeader').val().trim();
        let commentText = $('#commentText').val().trim();


        if (name.length == 0 ||
            email.length == 0 ||
            commentHeader.length == 0) {
            alert("Please input all fills.");
            return;
        }
        $.ajax({
            url: '/comment/add',
            type: 'get',
            data: {
                postId: postId,
                name: name,
                email: email,
                commentHeader: commentHeader,
                commentText: commentText
            },
            success: data => {

                let commentCount = parseInt($("#count-comment").text()) + 1;
                if (commentCount <= 1) {
                    $("#count-comment").text(commentCount + " Comment");
                } else {
                    $("#count-comment").text(commentCount + " Comments");
                }
                
                $(".comment-list").prepend(`
                                        <div class="single-comment justify-content-between d-flex mb-2">
                                            <div class="user justify-content-between">
                                                <div class="thumb d-flex">
                                                        <div><a class="h4" href="#">${name}</a></div>
                                                </div>
                                                <div>
                                                        <p class="date h6">${commentHeader}</p>
                                                        <p class="comment">${commentText}</p>
                                                </div>
                                            </div>
                                        </div>
                                        `);


            }

        });
    });
</script>

FA.JustBlog/FA.JustBlog.MVC/Views/Post/GetPostByCategory.cshtml
@using FA.Common
@using FA.JustBlog.Models.Models.Post
@model IEnumerable<PostModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 @foreach (var item in Model)
{
    <div class="item">
        <div class="post_s_item">
            <div class="post_text">
                <a class="cat" href="@Url.Action("Detail", "Post", new { Id = item.Id})">@item.CategoryName</a>
                <a href="@Url.Action("Detail", "Post", new { Id = item.Id})"><h4>@item.Title</h4></a>
                <p>@item.ShortDescription</p>
                <div class="date">
                    <a href="#"><i class="fa fa-calendar" aria-hidden="true"></i>@TimeOn.Time(item.PostedOn)</a>
                    <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <hr class="my-4" />
}   

FA.JustBlog/FA.JustBlog.MVC/Views/Post/GetPostByTag.cshtml
@using FA.Common
@using FA.JustBlog.Models.Models.Post
@model IEnumerable<PostModel>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 @foreach (var item in Model)
{
    <div class="item">
        <div class="post_s_item">
            <div class="post_text">
                <a class="cat" href="@Url.Action("Detail", "Post", new { Id = item.Id})"><h4>@item.Title</h4></a>
                <p>@item.ShortDescription</p>
                <div class="date">
                    <a href="#"><i class="fa fa-calendar" aria-hidden="true"></i> @TimeOn.Time(item.PostedOn)</a>
                    <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <hr class="my-4" />
} 

FA.JustBlog/FA.JustBlog.MVC/Views/Post/Index.cshtml
@using FA.Common
@using FA.JustBlog.Models.Models.Post
@using System.Collections.Generic
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common
@model IPagedList<PostModel>

@{
	ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<h1>All Post</h1>
<hr />
@foreach (var item in Model)
{
    <div class="item">
        <div class="post_s_item">
            <div class="post_text">
                 <a class="cat" href="@Url.Action("Details" , "Post" , new {@year =
                item.PostedOn.Year, @month = item.PostedOn.Month.ToString("00"),
               @title = item.UrlSlug})" ><h2>@item.Title</h2></a>
                Category : <a class="cat" style="text-decoration-line : underline  " href="@Url.Action("GetPostByCategory", "Post", new { category = item.CategoryName})">@item.CategoryName</a>
                 <br />
                Tag :
                @foreach(var i in item.TagList){
                    <a style="background-color : black ; color : white ; font : bold ; text-decoration-line : underline ; padding : 4px" class="cat" href="@Url.Action("GetPostByTag", "Post", new { tag = i.Name})">@i.Name</a>
                }
                <br />
                <div class="date text-secondary">
                    <i class="fa fa-calendar" aria-hidden="true"></i>  Posted
                    @TimeOn.Time(item.PostedOn)
                    with rate @item.Rate by @item.ViewCount @(item.ViewCount <= 1 ? "view" : "views")
                </div>
                <i class="text-muted">@item.ShortDescription</i>
            </div>
        </div>
    </div>
    <hr class="my-4" />
}


<div class="pull-right">
    @Html.PagedListPager((IPagedList)Model,
    page => Url.Action("Index",
    new {page}),
    new PagedListRenderOptions
    {
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" },
    LinkToPreviousPageFormat = "Trước",
    LinkToNextPageFormat = "Sau",
    LinkToFirstPageFormat = "Trang Đầu",
    LinkToLastPageFormat = "Trang Cuối",
    Display = PagedListDisplayMode.IfNeeded,
    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
    DisplayLinkToLastPage = PagedListDisplayMode.Always
    })
</div>